### ISSUE TITLE
Potential problem with multiple org.osgi.service.component.annotations packages

### ISSUE THREAD

**Issue by merks** [eclipse-equinox/equinox#157]
Testing the platform's 4.26 I-Build for split-package signature problems, this one crops up:

1. **org.osgi.service.component.annotations**
   - _[org.eclipse.osgi.services 3.11.100.v20221006-1531, org.osgi.service.component.annotations 1.5.0.202109301733]_
   - {CN=Eclipse.org Foundation, Inc., OU=IT, O=Eclipse.org Foundation, Inc., L=Ottawa, ST=Ontario, from=2022-05-02, to=2024-05-22}
   - unsigned

The first one is this and is jar signed:

https://download.eclipse.org/oomph/archive/reports-extra/4.26-I-builds/download.eclipse.org/eclipse/updates/4.26-I-builds/I20221111-1800/index/org.eclipse.osgi.services_3.11.100.v20221006-1531.html

The second one is this and is PGP signed:

https://download.eclipse.org/oomph/archive/reports-extra/4.26-I-builds/download.eclipse.org/eclipse/updates/4.26-I-builds/I20221111-1800/index/org.osgi.service.component.annotations_1.5.0.202109301733.html

Should this one 

![image](https://user-images.githubusercontent.com/208716/201461687-a0fb1ec1-01d1-4653-842c-2cc5382a2be0.png)

really have a copy of the content from this one

![image](https://user-images.githubusercontent.com/208716/201461645-0935ed34-b37d-4902-8749-17de05941ab1.png)

I suppose running system will just pick one of two packages and not actually encounter a problem with loading a class form one package and then a different class from the other package, but it still seems odd to duplicate the content.  Though I guess it's not actually a duplicate because one is version 1.3 and the other version 1.5.

Is this state actually the desired correct one?

**Comment by laeubi** [comment]
Today I think the most suitable solution would be to not publish org.eclipse.osgi.services at all (we can always use the official artifact from the osgi alliance instead). Beside that. all these annotations are actually class retention annotations, so should never be loaded at runtime at all.

**Comment by HannesWell** [comment]
This situation is expected (but not desired) since the transition to OSGi-bundles from Maven-Central has started in https://github.com/eclipse-equinox/equinox/issues/18 but is not yet completed. It is currently blocked by https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/239 not being available, which was blocked by https://github.com/eclipse-equinox/p2/pull/64. But we resolved the latter we just have to wait until that is available in Tycho and then (hopefully) can proceed after the december SimRel.

Unfortunately the strategy to replace the previously embedded OSGi sources by bundles from Maven-Central and simply re-exporting them until `o.e.osgi.services` is eventually removed cannot be applied to the packages you mentioned because of https://github.com/eclipse-equinox/equinox/issues/18#issuecomment-1157433300.
However, after the december release we should eventually be able to start their fade-out.

**Comment by laeubi** [comment]
> This situation is expected (but not desired)

I think there is actually nothing special or something one must be concerned, this is not a split package and just a regular package in different versions.
