### ISSUE TITLE
Incorrect version in module-info

### ISSUE THREAD

**Issue by fipro78** [eclipse-equinox/equinox#17]
I just noticed that the module-info of org.eclipse.osgi has the version 3.17.200-SNAPSHOT while the bundle itself has the version 3.17.200.v20220215-2237 in the MANIFEST.MF.

**Comment by tjwatson** [comment]
Now that we are moving to use BND to generate the module-info class, we have moved to striping off the qualifier from the module-info version (see #53).  I'm going to close this issue because it was about the incorrect version being set with our usage of modetect.  There is still some work that needs to be done to make sure the BND production of module-info is correct #27.
