### ISSUE TITLE
JRE-1.1.profile has no system packages

### ISSUE THREAD

**Issue by laeubi** [eclipse-equinox/equinox#571]
The system packages for the profile is empty:

https://github.com/eclipse-equinox/equinox/blob/cf85dc1c86b3df415610a30c981fa7ed2ffef6a1/bundles/org.eclipse.osgi/JRE-1.1.profile#L14

This currently leads to a warning in Tycho builds

> [09:31:29.975] [WARNING] No system packages found in profile nor toolchain for JRE-1.1, using current JRE system packages.

to reduce warnings in builds I'd like to get rid of this, the question is is it correct that for a JRE-1.1 VM there are literally no system packages or can be simply copy the ones from here for example:
https://github.com/eclipse-equinox/equinox/blob/master/bundles/org.eclipse.osgi/OSGi_Minimum-1.1.profile

**Comment by tjwatson** [comment]
I'm surprised there are any projects that try to use JRE-1.1, let alone fine a java compiler that can compile down to something that low.  I doubt it makes any difference what you put in there since I doubt it can really be used for a real scenario anymore.  With that said, I guess you can copy the content of https://github.com/eclipse-equinox/equinox/blob/master/bundles/org.eclipse.osgi/OSGi_Minimum-1.0.profile for the system packages.

A while ago I wanted to delete all these profiles except for the ones related to Java 8 since these are the only ones the framework could ever use at runtime.  The Java 9 one is never used because we generate the system packages based on JPMS.  But it surprised me that we have all these users of these files.  At any rate, there are no profiles for Java versions > 9 so tycho and others must get this information some other way, right?

**Comment by laeubi** [comment]
> I'm surprised there are any projects that try to use JRE-1.1, let alone find a java compiler that can compile down to something that low.

It is not really used in a build, it is just that Equinox mention it in the [profile.list](https://github.com/eclipse-equinox/equinox/blob/master/bundles/org.eclipse.osgi/profile.list) and there it is parsed and issues an warning because it has no system packages. So another one would be to simply delete it altogether.

> At any rate, there are no profiles for Java versions > 9 so tycho and others must get this information some other way, right?

For any JVM > 8 that does not have a profile Tycho automatically generates one.

**Comment by tjwatson** [comment]
> So another one would be to simply delete it altogether.

+1 to delete.

**Comment by HannesWell** [comment]
> At any rate, there are no profiles for Java versions > 9 so tycho and others must get this information some other way, right?

In PDE there is a bit of logic for that, which was introduced with https://github.com/eclipse-pde/eclipse.pde/pull/693.
I don't want to replicate it here, but for the `JRE-1.1` and `J2SE-1.2` profiles the list of `java*` packages is hard coded in PDE (I have derived it from ancient JDK's I found in some Oracle archives):
https://github.com/eclipse-pde/eclipse.pde/blob/203a2c10e860b6c5e2ddde659d6f1e68b804ae49/build/org.eclipse.pde.build/src/org/eclipse/pde/internal/build/site/PDEState.java#L582-L642

**Comment by HannesWell** [comment]
Just for the record: there is no official [OSGi Execution Environment Names](https://docs.osgi.org/reference/eenames.html) named `JRE-1.1`. There is only `CDC-1.1/Foundation-1.1`, `CDC-1.1/PersonalBasis-1.1` or `CDC-1.1/PersonalJava-1.1` but I have never seen any of these in use (but I only use OSGi with Eclipse).

**Comment by iloveeclipse** [comment]
The changes started here require PDe update, see https://github.com/eclipse-pde/eclipse.pde/issues/1231

**Comment by HannesWell** [comment]
> Given that this creates some disturbance it might be good to restore the profile and simply add the packages @HannesWell was derived for PDE a while back.

Although I'm usually in favor of going forward and try to fix 'mistakes' done in the past (from the previous conversation I assume it is considered as such) in this case it requires a lot of downstream adjustments. And as it was indicated in https://github.com/eclipse-pde/eclipse.pde/issues/1231#issuecomment-2056738410 and https://github.com/eclipse-pde/eclipse.pde/issues/1231#issuecomment-2056841517 if we keep this removed we would have to add special handling to PDE in order to support old TPs. And there are even remains in Equinox as mentioned in the linked comments.
Also BND has such JRE-1.1:
https://github.com/bndtools/bnd/blob/5d0218836873d57ea7fba7ec57ceef075238ef48/biz.aQute.bndlib/src/aQute/bnd/build/model/EE.java#L37

So overall I also think that's not worth the effort to keep it removed and I'm keen to revert the removal and instead update to the system-packages currently hard-coded in PDE. We then have also have to (partially) revert https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/425, otherwise https://github.com/eclipse-pde/eclipse.pde/issues/1231 cannot be resolved.

**Comment by iloveeclipse** [comment]
> We then have also have to (partially) revert [eclipse-jdt/eclipse.jdt.debug#425](https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/425)

I'm wondering about **partially** part of this. Why not just revert https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/425?
@HannesWell : Do you plan to provide a PR with the partial revert?

**Comment by iloveeclipse** [comment]
> If you want to have it earlier, please feel free to do it earlier. :)

https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/431
