### ISSUE TITLE
[win] ServletTest fails on I-Builds since I20240411-1800

### ISSUE THREAD

**Issue by jukzi** [eclipse-equinox/equinox#599]
4 tests consecutive fail in windows i-builds 

for example
https://download.eclipse.org/eclipse/downloads/drops4/I20240416-0300/testresults/html/org.eclipse.equinox.http.servlet.tests_ep432I-unit-win32-java17_win32.win32.x86_64_17.html

```
java.lang.AssertionError: Content-Length expected:<[20910]> but was:<[20655]>
at org.eclipse.equinox.http.servlet.tests.ServletTest.test_ResourceRangeRequest_Complete(ServletTest.java:2004)

```

```
Content-Range expected:<[bytes 1000-9999/20910]> but was:<[bytes 1000-9999/20655]>
at org.eclipse.equinox.http.servlet.tests.ServletTest.test_ResourceRangeRequest_WithRange(ServletTest.java:2037)

```

```
java.lang.AssertionError: Content-Length expected:<[20910]> but was:<[20655]>
at org.eclipse.equinox.http.servlet.tests.ServletTest.test_ResourceRangeRequest_WithRange_customContext(ServletTest.java:2076)

```

```
org.junit.ComparisonFailure: expected:<1[
]
> but was:<1[]
>
at org.eclipse.equinox.http.servlet.tests.ServletTest.test_ServletContextHelper11(ServletTest.java:3119)

```

i could not reproduce locally.

**Comment by HannesWell** [comment]
That's a regression from https://github.com/eclipse-equinox/equinox/pull/586.
The file served by the test-server is actually a text file and therefore its actual content length is different on Windows and Linux due to the different default line-endings (`LF` vs `CRLF`) on these platforms.
With https://github.com/eclipse-equinox/equinox/pull/586 I adjusted the expectations accordingly so that the `ServletTest` passes locally on Windows too and in the then added full GH workflow for Windows. But this does not work at the same time, if the test-resources are packed on Linux with LF line-ending and but the tests run on Windows.

With https://github.com/eclipse-equinox/equinox/pull/604 I now introduced corresponding `.gitattributes` that ensure the test-resources are checked-out with LF line-endings even on Windows. An existing
